image: mikebarkmin/gitpod-workspace-full-vnc-java-ipad

ports:
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - esbenp.prettier-vscode
    - openpatch.hyperbook-studio
