#!/usr/bin/env python3
"""
Carries ParityProbe and its expected values into the online IDE's test suite.

The desktop probe is the original. The browser cannot run it as it stands - there
are no packages, no imports and no main() in that dialect - so the statements are
lifted out and the print helper is inlined. Doing that by hand would let the two
drift, which is the very thing the probe exists to catch, so it is done here and
the result is generated, never edited.

    python3 scripts/parity-fixture.py            write the fixture
    python3 scripts/parity-fixture.py --check    fail if the committed one is stale
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROBE = ROOT / "src/examples/java/parity/ParityProbe.java"
EXPECTED = ROOT / "src/test/resources/parity/expected.txt"
FIXTURE = ROOT.parent / "online-ide/src/test/java/ScratchParityTest.java"

def statements() -> list[str]:
    """
    The body of valuesWithoutAStage(), with p(...) turned into println(...).

    Only that half: the browser's tests run in node, where there is no WebGL and
    so no Stage at all. See the method's own comment.
    """
    source = PROBE.read_text()
    body = source[source.index("static void valuesWithoutAStage()"):]
    body = body[body.index("{") + 1:]
    body = body[:body.rindex("}")].rstrip()
    body = body[:body.rindex("}")].rstrip()

    out = []
    for line in body.split("\n"):
        # p("key", value);  ->  println("key=" + value);
        line = re.sub(r'\bp\("([^"]+)",\s*(.+)\);\s*$', r'println("\1=" + \2);', line)
        out.append(line[4:] if line.startswith("    ") else line)
    while out and not out[-1].strip():
        out.pop()
    return out


def keys() -> list[str]:
    """The keys those statements print, in order."""
    return re.findall(r'println\("([^"=]+)=', "\n".join(statements()))


def known_gap(value: str) -> str:
    """
    Drops the ".0" Java puts on a whole double.

    The browser prints `50` where Java prints `50.0`, because the IDE hands a
    double straight to JavaScript's own string conversion. That is how the online
    IDE prints every double in every Java program, not something about this
    library, and it is not going to change - so it is the one difference this
    test is built to look past rather than a drift waiting to be fixed.

    A wrong *value* is still caught: 50.0 against 60 does not match either way.
    Keep it to this: anything else the two disagree about is a real difference
    and belongs in the output, not in here.
    """
    return re.sub(r"^(-?\d+)\.0$", r"\1", value)


def build() -> str:
    if not EXPECTED.exists():
        sys.exit(f"no {EXPECTED} yet - run ./scripts/parity.sh --record first.")
    recorded = dict(
        line.split("=", 1)
        for line in EXPECTED.read_text().splitlines() if "=" in line
    )
    wanted = keys()
    missing = [k for k in wanted if k not in recorded]
    if missing:
        sys.exit(f"parity-fixture: {missing} is not in {EXPECTED} - re-record first.")
    expected = "".join(f"{k}={known_gap(recorded[k])}\n" for k in wanted)
    escaped = expected.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    return (
        "// GENERATED by scripts/parity-fixture.py in the scratch-for-java repository.\n"
        "// Do not edit: change src/examples/java/parity/ParityProbe.java there instead,\n"
        "// re-record with ./scripts/parity.sh --record and run the script again.\n"
        "//\n"
        "// Every value below is one the desktop library prints. Where this test fails,\n"
        "// the browser and the desktop have drifted apart, and the output of the two\n"
        "// says exactly where.\n"
        "//\n"
        "// Only the stage-free half of the probe is here. A Stage needs WebGL, which\n"
        "// node has not got, so sprite geometry and the hitbox cannot be checked this\n"
        "// way - scripts/parity.sh holds the desktop to those, and ScratchTest.java\n"
        "// holds the browser to the same signatures.\n"
        "//\n"
        "// A whole double reads as `50` here and `50.0` on the desktop, because the\n"
        "// IDE prints every double through JavaScript's own string conversion. That\n"
        "// is settled and will not change, so the expected values below have had the\n"
        "// trailing .0 taken off. A wrong value still fails.\n"
        "\n"
        "/**::\n"
        " * Scratch the browser reports what the desktop reports\n"
        ' * { "libraries": ["scratch"], "expectedOutput": "' + escaped + '" }\n'
        " */\n"
        + "\n".join(statements())
        + "\n"
    )


def main() -> None:
    check = "--check" in sys.argv
    if not FIXTURE.parent.exists():
        message = f"the online IDE is not beside this repository ({FIXTURE.parent})"
        if check:
            print(f"parity-fixture: skipped, {message}")
            return
        sys.exit(f"parity-fixture: {message}")

    wanted = build()
    if check:
        current = FIXTURE.read_text() if FIXTURE.exists() else ""
        if current != wanted:
            sys.exit("parity-fixture: the online IDE's copy is out of date - "
                     "run python3 scripts/parity-fixture.py")
        print("parity-fixture: the online IDE's copy is up to date.")
        return

    FIXTURE.write_text(wanted)
    print(f"parity-fixture: wrote {FIXTURE} "
          f"({len(statements())} lines, {len(keys())} of "
          f"{len(EXPECTED.read_text().splitlines())} values)")


if __name__ == "__main__":
    main()
