name: JavaDocs

on:
  push:
    branches:
      - main

jobs:
  javadocs:
    runs-on: ubuntu-latest

    steps:

      - name: Generate Javadocs
        run: mvn -B javadoc:javadoc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Javadocs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/apidocs

      - name: Deploy Javadocs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
